// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dovpxivdnrkistyigjyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdnB4aXZkbnJraXN0eWlnanl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjY1MTIsImV4cCI6MjA3MjIwMjUxMn0.H5XRQBA0pnIg1z1bqJLK7Zvhah0M-wWB-G2csJEKhH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});